In [ ]:
#NumPy
#Langchain Gen AI Propt Engg
#Projects
Numerical Python or Number Python - 
-We can represent list of numbers in many formats
    -- list or tuple
    -- numpy
    -- tensors
-For AI model development we need vector representation of data . That can be acheived by numpy & tensors
-We cannot perform Maths and Physics opeations using list or tuple. We need numpy or tensors
-For CPU numpy is enough. If we work for BigData (GPU) prefer tensors


In [3]:
import numpy as np
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_core',
 '_distributor_init',


In [6]:
#-SUm, Min, Max, Mean, Variance, Standard Deviation
li=[10,20,30]
arr1=np.array(li)
arr1

array([10, 20, 30])

In [11]:
l2=[100,200,300]
arr2=np.array(l2)
arr3=arr1+arr2
arr3


array([110, 220, 330])

In [ ]:
#Elementwise  operations
l1=[10,20,30,40]
l2=

In [13]:
arr3.max()

330

In [14]:
arr3.mean()

220.0

In [1]:
import numpy as np
np.__version__

'1.26.4'

In [5]:
#numpy array
l=[10,20,30,40]
arr1=np.array(l)
arr1

array([10, 20, 30, 40])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
l2=[100,200,300,400]
arr2=np.array(l2)
arr2

array([100, 200, 300, 400])

In [9]:
arr1+arr2

array([110, 220, 330, 440])

In [10]:
#element wise Operation
print(arr1)
print(arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[10 20 30 40]
[100 200 300 400]
[110 220 330 440]
[ -90 -180 -270 -360]
[ 1000  4000  9000 16000]
[0.1 0.1 0.1 0.1]


In [ ]:
l1=range(1,10)

In [12]:
import time
start = time.time()
l1=range(1,1000000)
l2=range(1,1000000)
[i*j for i,j in zip(l1,l2)]
end = time.time()
print(f' time taken:{end-start}')

 time taken:0.12283897399902344


In [19]:
import time
start=time.time()
arrr1=np.arange(1,1000000)
arrr2=np.arange(1,1000000)
arr3=arrr1*arrr2
end=time.time()
print(f' time taken:{end-start}')

 time taken:0.009952783584594727


In [20]:
len(arr3)

999999

In [23]:
#Numpy Dimensions
# 1 Dimension
import numpy as np
l1=[10,20,30,40]
#creat Array
arr1=np.array(l1)
arr1

array([10, 20, 30, 40])

In [24]:
arr1.ndim

1

In [25]:
arr1.shape

(4,)

In [26]:
arr1.size

4

In [28]:
#matrix
#2 Dimesional
l1=[1, 2, 3, 4]
l2=[10, 20, 30, 40]
#combine both
l=[l1,l2]
arr2=np.array(l)
arr2

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [30]:
arr2.ndim

2

In [31]:
arr2.shape


(2, 4)

In [32]:
arr2.size

8

In [33]:
#matrix
l1=[1, 2, 3, 4]
l2=[10, 20, 30, 40]
l3=[100, 200, 300, 400]
#combine both
l=[l1,l2,l3]
arr3=np.array(l)
arr3

array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400]])

In [34]:
arr3.shape
#3 lists with 4 values

(3, 4)

In [35]:
arr3.size

12

In [36]:
arr3.ndim

2

In [ ]:
#matrix
l1=[1, 2, 3, 4]
l2=[10, 20, 30, 40]
l3=['A','B','C','D']

In [38]:
#5,4,2,4,,5
l1=[1,1,1,1,1]
l2=[l1,l1,l1,l1]
l3=[l2,l2]
l4=[l3,l3,l3,l3]
l5=[l4,l4,l4,l4,l4]
arr=np.array(l5)


array([[[[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]],


        [[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]],


        [[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]],


        [[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]]],



       [[[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],



In [39]:
arr.shape

(5, 4, 2, 4, 5)

In [40]:
arr.size

800

In [48]:
# 3,2,3

a=[1,2,3]
b=[4,5,6]
c=[7,8,9]
d=[10,11,12]
e=[13,14,15]
f=[16,17,18]
l21=[a,b]
l22=[c,d]
l23=[e,f]
###################################
l3=[l21,l22,l23]
arr=np.array(l3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [49]:
arr.shape

(3, 2, 3)

In [1]:
#Maths with numpy
import numpy as mp
dir(np)

NameError: name 'np' is not defined

In [50]:
arr.ndim

3